### ISSUE TITLE
Add a frontend interface to fetch data from backend

### ISSUE THREAD

**Issue by NielsPraet** [SELab-2/OSOC-1#162]
To be able to correctly fetch data from the backend, we need to do a couple of other things first. Here's a checklist:
- [x] Add the ability to use refresh tokens to renew the access token (#114)
- [x] Add a session tracker (#160)
- [ ] Create a singleton object that we can use for interacting with our backend (#161)
- [ ] Create a custom React hook to easily access this singleton object (Can also be done in #161)
